#!/usr/bin/env python3
"""@brief FFmpeg-based H.264 MP4 transcoder command.

@details Converts one input video to H.264/AAC MP4 using fixed FFmpeg
arguments required by CLI contract. Output path is generated by appending
`.mp4` to the input filename and preserving the input directory.
@satisfies REQ-057, REQ-055, REQ-056
"""

import os
from pathlib import Path

from shell_scripts.utils import print_error, require_commands

## @var PROGRAM
#  @brief CLI program identifier used in usage text.
#  @satisfies DES-008
PROGRAM = "shellscripts"
## @var DESCRIPTION
#  @brief Command description exposed in global help index.
#  @satisfies PRJ-002, DES-008, REQ-057
DESCRIPTION = "Convert one video to H.264 MP4 via ffmpeg."


def print_help(version):
    """@brief Print command usage for `video2h264`.

    @details Emits deterministic help text describing required positional input
    and output naming semantics.
    @param version {str} CLI version string for usage suffix.
    @return {None} Writes help text to stdout.
    @satisfies DES-008, REQ-057
    """

    print(f"Usage: {PROGRAM} video2h264 <input-video> ({version})")
    print()
    print("video2h264 options:")
    print("  <input-video>  - Input video file path (required).")
    print("  --help         - Show this help message.")
    print()
    print("Output path is generated as <input-video>.mp4 in the input directory.")


def run(args):
    """@brief Execute H.264 transcode command with fixed FFmpeg parameters.

    @details Validates input argument presence and file existence, then replaces
    current process with `ffmpeg` execution using required libx264 profile,
    level, CRF, pixel format, and AAC audio bitrate options.
    @param args {list[str]} Expected single positional input-video path.
    @return {int} `1` on argument/validation failure; otherwise no return on exec.
    @satisfies REQ-057, REQ-055, REQ-056
    """

    if len(args) != 1 or args[0].startswith("-"):
        print_error("Input video file required.")
        print_help("")
        return 1

    input_file = Path(args[0])
    if not input_file.is_file():
        print_error(f"File not found: {input_file}")
        return 1

    output_file = input_file.parent / f"{input_file.name}.mp4"
    cmd = [
        "ffmpeg",
        "-i",
        str(input_file),
        "-c:v",
        "libx264",
        "-profile:v",
        "high",
        "-level",
        "4.1",
        "-crf",
        "20",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-b:a",
        "192k",
        str(output_file),
    ]

    require_commands(cmd[0])
    os.execvp(cmd[0], cmd)
